# Generated by Django 4.2.7 on 2023-11-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('ContactId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=40)),
                ('Email', models.TextField(max_length=10, null=True)),
                ('ContactNumber', models.TextField(max_length=10)),
                ('CompnayName', models.TextField(max_length=10)),
                ('Message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
