# Generated by Django 4.2.6 on 2023-11-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.TextField(max_length=40)),
                ('middleName', models.TextField(max_length=10, null=True)),
                ('lastName', models.TextField(max_length=10)),
                ('emailId', models.TextField(max_length=10)),
                ('mobileNumber', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1, null=True)),
                ('DOB', models.TextField(max_length=40)),
                ('address', models.TextField(max_length=1000)),
                ('password', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('SalaryId', models.AutoField(primary_key=True, serialize=False)),
                ('MonthlySalary', models.TextField(max_length=40)),
                ('TotalSalary', models.TextField(max_length=10, null=True)),
                ('GrossSalary', models.TextField(max_length=10)),
                ('TaxSlab', models.TextField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
